sudo: required
language: java

branches:
  only:
    - rails_2_develop
    - rails_2_maintenance

jobs:
  include:
    - name: Linux OpenJDK 11
      os: linux
      dist: trusty
      jdk: openjdk11
    - name: Linux OpenJDK 13
      os: linux
      dist: trusty
      jdk: openjdk13
    - name: MacOS OpenJDK 11
      os: osx
      osx_image: xcode10.1
    - name: MacOS OpenJDK 13
      os: osx
      osx_image: xcode11.3
      script: mvn clean test