sudo: required
language: java

branches:
  only:
    - rails_2_develop
    - rails_2_maintenance

jobs:
  include:
    - stage: Test
      name: Linux OpenJDK 11
      os: linux
      dist: trusty
      jdk: openjdk11
      script:
        - mvn clean test
    - stage: Test
      name: Linux OpenJDK 13
      os: linux
      dist: trusty
      jdk: openjdk13
      script:
        - mvn clean test
    - stage: Test
      name: MacOS OpenJDK 11
      os: osx
      osx_image: xcode10.1
      script:
        - mvn clean test
    - stage: Test
      name: MacOS OpenJDK 13
      os: osx
      osx_image: xcode11.3
      script:
        - mvn clean test