sudo: required
dist: trusty
language: java

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7

branches:
  only:
  - rails_2_develop
  - rails_2_maintenance

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq lib32z1 lib32ncurses5 lib32bz2-1.0 zlib1g:i386 genisoimage