sudo: required
os: linux
dist: trusty
language: java

branches:
  only:
  - rails_2_develop
  - rails_2_maintenance

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq lib32z1 lib32ncurses5 lib32bz2-1.0 zlib1g:i386 genisoimage

jobs:
  include:
  - name: Linux Oracle JDK 8
    jdk: oraclejdk8
  - name: Linux Oracle JDK 9
    jdk: oraclejdk9
  - name: Linux Oracle JDK 10
    jdk: oraclejdk10
  - name: Linux Oracle JDK 11
    jdk: oraclejdk11
  - name: Linux OpenJDK 11
    jdk: openjdk11