name: Java CI with Maven

on:
  push:
    branches: [ rails_2_develop ]
  pull_request:
    branches: [ rails_2_develop ]

jobs:
  jdk11:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - name: Tests - OpenJDK 11
        run: mvn -B package --file pom.xml

  windows:
    name: Build - Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk
      - name: Execute Tests
        run: mvn -B clean test --file pom.xml
      - name: Build jar
        run: mvn -B clean package --file pom.xml
      - name: Create Installer
        run: jpackage --verbose --name rails-18xx --icon ./src/main/resources/build/rails.ico --app-version 2.1.0 --input target --main-jar rails-2.2-alpha-all.jar --win-menu --win-shortcut
      - name: Upload Installer
        uses: actions/upload-artifact@v1
        with:
          name: exe
          path: rails-18xx-2.1.0.exe

  ubuntu:
    name: Build - Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk
      - name: Execute Tests
        run: mvn -B clean test --file pom.xml
      - name: Build jar
        run: mvn -B clean package --file pom.xml
      - name: Debug
        run: man jpackage | cat
      - name: Create Installer
        run: jpackage --verbose --name rails-18xx --icon ./src/main/resources/build/rails.png --app-version 2.1.0 --input target --main-jar rails-2.2-alpha-all.jar --linux-package-name rails-18xx --linux-app-category games --linux-shortcut
      - name: Upload Installer
        uses: actions/upload-artifact@v1
        with:
          name: deb
          path: rails-18xx_2.1.0-1_amd64.deb

  macos:
    name: Build - MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk
      - name: Execute Tests
        run: mvn -B clean test --file pom.xml
      - name: Build jar
        run: mvn -B clean package --file pom.xml
      - name: Create Installer
        run: jpackage --verbose --name rails-18xx --icon ./src/main/resources/build/rails.ico --app-version 2.1.0 --input target --main-jar rails-2.2-alpha-all.jar --mac-package-name rails-18xx
      - name: Upload Installer
        uses: actions/upload-artifact@v1
        with:
          name: dmg
          path: rails-18xx-2.1.0.dmg

  publish:
    name: Publish Installers
    needs: [windows, ubuntu, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download exe
        uses: actions/download-artifact@v1
        with:
          name: exe
      - name: Download deb
        uses: actions/download-artifact@v1
        with:
          name: deb
      - name: Download dmg
        uses: actions/download-artifact@v1
        with:
          name: dmg
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
      - name: Upload exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./exe/rails-18xx-2.1.0.exe
          asset_name: rails-18xx-2.1-alpha.exe
          asset_content_type: application/octet-stream
      - name: Upload deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./deb/rails-18xx_2.1.0-1_amd64.deb
          asset_name: rails-18xx-2.1-alpha.deb
          asset_content_type: application/octet-stream
      - name: Upload dmg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dmg/rails-18xx-2.1.0.dmg
          asset_name: rails-18xx-2.1-alpha.dmg
          asset_content_type: application/octet-stream