name: Java CI with Maven

on:
  push:
    branches: [ rails_2_develop ]
  pull_request:
    branches: [ rails_2_develop ]

jobs:
  jdk11:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - name: Tests - OpenJDK 11
        run: mvn -B package --file pom.xml

  windows:
    name: Build - Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk
      - name: Execute Tests
        run: mvn -B clean test --file pom.xml
      - name: Build jar
        run: mvn -B clean package --file pom.xml
      - name: Create Installer
        run: jpackage --name rails-packaged --input target --main-jar rails-2.2-alpha-all.jar
      - name: Upload Installer
        uses: actions/upload-artifact@v1
        with:
          name: exe
          path: rails-packaged-1.0.exe

  ubuntu:
    name: Build - Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk
      - name: Execute Tests
        run: mvn -B clean test --file pom.xml
      - name: Build jar
        run: mvn -B clean package --file pom.xml
      - name: Create Installer
        run: jpackage --name rails-packaged --input target --main-jar rails-2.2-alpha-all.jar
      - name: Upload Installer
        uses: actions/upload-artifact@v1
        with:
          name: deb
          path: rails-packaged_1.0-1_amd64.deb

  macos:
    name: Build - MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk
      - name: Execute Tests
        run: mvn -B clean test --file pom.xml
      - name: Build jar
        run: mvn -B clean package --file pom.xml
      - name: Create Installer
        run: jpackage --name rails-packaged --input target --main-jar rails-2.2-alpha-all.jar
      - name: Upload Installer
        uses: actions/upload-artifact@v1
        with:
          name: dmg
          path: rails-packaged-1.0.dmg

  publish:
    name: Publish Installers
    needs: [windows, ubuntu, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download exe
        uses: actions/download-artifact@v1
        with:
          name: exe
          path: rails-packaged-1.0.exe
      - name: Download deb
        uses: actions/download-artifact@v1
        with:
          name: deb
          path: rails-packaged_1.0-1_amd64.deb
      - name: Download dmg
        uses: actions/download-artifact@v1
        with:
          name: dmg
          path: rails-packaged-1.0.dmg
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
      - name: Upload exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rails-packaged-1.0.exe
          asset_name: rails-packaged-1.0.exe
      - name: Upload deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rails-packaged_1.0-1_amd64.deb
          asset_name: rails-packaged_1.0-1_amd64.deb
      - name: Upload dmg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rails-packaged-1.0.dmg
          asset_name: rails-packaged-1.0.dmg