name: Java CI with Maven

on:
  push:
    branches: [ rails_2_develop ]
  pull_request:
    branches: [ rails_2_develop ]

jobs:
  jdk8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Tests - OpenJDK 8 
      run: mvn -B package --file pom.xml
  jdk11:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
    - name: Tests - OpenJDK 11 
      run: mvn -B package --file pom.xml
