name: Create Releases with Gradle

on:
  push:
    tags:
      - 'releases/*'

jobs:
  jdk11:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          java-package: jdk
      - name: Execute Tests
        run: ./gradlew clean test

  ubuntu:
    name: Build Ubuntu Installer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          java-package: jdk
      - name: Get the version
        id: tagName
        run: echo "tag=${GITHUB_REF_NAME#releases/}" >> $GITHUB_OUTPUT
      - name: Execute Tests
        run: ./gradlew clean test
      - name: Build jar
        run: ./gradlew -Pversion=${{ steps.tagName.outputs.tag }} clean build
      - name: Create Deb Installer
        run: ./gradlew -Pversion=${{ steps.tagName.outputs.tag }} buildDebPackage
      - name: Create Rpm Installer
        run: ./gradlew -Pversion=${{ steps.tagName.outputs.tag }} buildRpmPackage
      - name: Rename Installers
        run: ./gradlew renameExecutables
      - name: Upload Deb Installer
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: rails-18xx.deb
      - name: Upload Rpm Installer
        uses: actions/upload-artifact@v4
        with:
          name: rpm
          path: rails-18xx.rpm

  windows:
    name: Build Windows Installers
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          java-package: jdk
      - name: Get the version
        id: tagName
        shell: bash
        run: echo "tag=${GITHUB_REF_NAME#releases/}" >> $GITHUB_OUTPUT
      - name: Execute Tests
        run: ./gradlew clean test
      - name: Build jar
        run: ./gradlew -Pversion="${{ steps.tagName.outputs.tag }}" clean build
      - name: Create Exe Installer
        run: ./gradlew -Pversion="${{ steps.tagName.outputs.tag }}" buildExePackage
      - name: Rename Installer
        run: ./gradlew renameExecutables
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: rails-18xx.exe

  macos:
    name: Build MacOS Installers
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          java-package: jdk
      - name: Get the version
        id: tagName
        run: echo "tag=${GITHUB_REF_NAME#releases/}" >> $GITHUB_OUTPUT
      - name: Execute Tests
        run: ./gradlew clean test
      - name: Build jar
        run: ./gradlew -Pversion=${{ steps.tagName.outputs.tag }} clean build
      - name: Create Dmg Installer
        run: ./gradlew -Pversion=${{ steps.tagName.outputs.tag }} buildpkgPackage
      - name: Rename Installer
        run: ./gradlew renameExecutables
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: pkg
          path: rails-18xx.pkg

  publish:
    name: Publish Installers
    needs: [windows, ubuntu, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get the version
        id: tagName
        run: echo "tag=${GITHUB_REF_NAME#releases/}" >> $GITHUB_OUTPUT
      - name: Download exe
        uses: actions/download-artifact@v4
        with:
          name: exe
      - name: Download deb
        uses: actions/download-artifact@v4
        with:
          name: deb
      - name: Download rpm
        uses: actions/download-artifact@v4
        with:
          name: rpm
      - name: Download pkg
        uses: actions/download-artifact@v4
        with:
          name: pkg
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: releases/${{ steps.tagName.outputs.tag }}
          name: ${{ steps.tagName.outputs.tag }}
          body: |
            Rails-18xx version ${{ steps.tagName.outputs.tag }}
          draft: false
          prerelease: true
          files: |
            rails-18xx.exe
            rails-18xx.deb
            rails-18xx.rpm
            rails-18xx.pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
